# Generated by Django 3.2.4 on 2022-03-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=34, unique=True, verbose_name='图片名字')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
                ('zh_with_image_working_pool_now', models.PositiveIntegerField(default=0, verbose_name='该标注哪个看图片的了')),
                ('is_project_work_total', models.PositiveSmallIntegerField(verbose_name='计划标注-工作的任务总量')),
                ('is_project_start_index', models.PositiveIntegerField(verbose_name='计划标注-从那个图片开始标注')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否是管理员')),
            ],
        ),
        migrations.CreateModel(
            name='FixZhWithImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_zh_with_image', models.TextField(verbose_name='对不看图片标注的中文译文fix之后的结果')),
                ('zh_with_image', models.TextField(null=True, verbose_name='看图片标注的中文译文')),
                ('zh_with_image_ppl', models.CharField(max_length=5, null=True, verbose_name='该中文译文的PPL值')),
                ('caption_id', models.PositiveIntegerField(verbose_name='该修正是对哪个英文描述修正的')),
                ('user_that_fixs_and_annots_it', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation.user')),
            ],
        ),
        migrations.CreateModel(
            name='FixInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_pos', models.PositiveSmallIntegerField(verbose_name='该修正在中文中开始的位置')),
                ('end_pos', models.PositiveSmallIntegerField(verbose_name='该修正在中文中结束的位置')),
                ('which_classification', models.PositiveSmallIntegerField(choices=[(1, '名词'), (2, '动词'), (3, '形容词'), (4, '数量'), (5, '其他错误'), (6, '描述细化')], verbose_name='哪个修正类型')),
                ('word_before_change', models.CharField(max_length=50)),
                ('word_after_change', models.CharField(max_length=50)),
                ('fix_zh_that_belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.fixzhwithimage')),
                ('user_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation.user')),
            ],
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_number', models.PositiveSmallIntegerField(verbose_name='该描述是第几个')),
                ('caption', models.TextField(verbose_name='英文描述')),
                ('caption_ppl', models.CharField(max_length=5, verbose_name='英文描述的PPL值')),
                ('zh_machine_translation', models.TextField(null=True, verbose_name='英文描述的机翻')),
                ('zh_machine_translation_ppl', models.CharField(max_length=5, null=True, verbose_name='机翻的PPL值')),
                ('is_ambiguity', models.BooleanField(null=True, verbose_name='第一阶段结束，确定下来是否有多种翻译')),
                ('correct_zh_number', models.PositiveSmallIntegerField(default=0, verbose_name='正确的那个中文的序号')),
                ('zhs_without_image', models.TextField(null=True, verbose_name='第一阶段结束，确定下来的不看图片译文')),
                ('zhs_ppl_without_image', models.TextField(null=True, verbose_name='不看图片译文的PPL值')),
                ('fix_zh_with_image_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation.fixzhwithimage')),
                ('image_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.image')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fixzhwithimage',
            constraint=models.UniqueConstraint(fields=('user_that_fixs_and_annots_it', 'caption_id'), name='user_fix_and_annot_zh_only_once'),
        ),
        migrations.AddConstraint(
            model_name='caption',
            constraint=models.UniqueConstraint(fields=('image_obj', 'caption_number'), name="this_image's_unique_caption"),
        ),
    ]
