# Generated by Django 3.2.4 on 2022-03-25 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caption',
            name='correct_zh_number',
        ),
        migrations.RemoveField(
            model_name='caption',
            name='is_ambiguity',
        ),
        migrations.RemoveField(
            model_name='caption',
            name='zhs_ppl_without_image',
        ),
        migrations.RemoveField(
            model_name='caption',
            name='zhs_without_image',
        ),
        migrations.AlterField(
            model_name='caption',
            name='fix_zh_with_image_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation.fixzhwithimage', unique=True),
        ),
    ]
