# Generated by Django 3.2.4 on 2022-03-25 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20220325_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='fix_zh_with_image_obj',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation.fixzhwithimage'),
        ),
    ]
