# Generated by Django 3.2.4 on 2022-03-25 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_alter_caption_fix_zh_with_image_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhWithoutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_thinks_caption_ambiguity', models.BooleanField(default=False, verbose_name='是否歧义')),
                ('correct_number', models.PositiveSmallIntegerField(default=0, verbose_name='正确的那个中文的序号')),
                ('zhs_without_image', models.TextField(verbose_name='不看图片标注的中文译文')),
                ('zhs_without_image_ppl', models.CharField(max_length=23, verbose_name='该中文译文的PPL值')),
                ('caption_id', models.PositiveIntegerField(verbose_name='该修正是对哪个英文描述修正的')),
                ('user_that_annots_it', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation.user')),
            ],
        ),
        migrations.AddField(
            model_name='caption',
            name='zh_without_image_obj',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation.zhwithoutimage'),
        ),
        migrations.AddConstraint(
            model_name='zhwithoutimage',
            constraint=models.UniqueConstraint(fields=('user_that_annots_it', 'caption_id'), name='user_annot_caption_only_once'),
        ),
    ]
