# Generated by Django 3.2.4 on 2022-03-25 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_auto_20220325_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_project_start_index',
            new_name='start_index_with_image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_project_work_total',
            new_name='work_total_with_image',
        ),
    ]
